### ISSUE TITLE
Widen the form fields

### ISSUE THREAD

**Issue by stevevance** [flinthillsdesign/wufoo-bootstrap-theme#4]
Thank you for making this theme. My Wufoo form now looks like the rest of my website. 

Do you know if it's possible to widen the form fields? The field settings in Wufoo are for a "large" field, but that's not reflected or acknowledged by the Bootstrap theme. I went through Wufoo's theme editor and field width isn't a changeable setting. 

<img width="548" alt="image" src="https://user-images.githubusercontent.com/1330459/75735321-04aacc80-5cc0-11ea-9f1e-6c55370039d3.png">

**Comment by davegaeddert** [comment]
Good question @stevevance. I think that should be possible... Is your expectation that "large" goes the full width of the form? It looks like that's what it does in the Wufoo form editor.

**Comment by stevevance** [comment]
That's my expectation - in Bootstrap the default form width is 100% of its parent container.

**Comment by davegaeddert** [comment]
Sorry this took so long -- been a crazy few weeks! Feel free to give it a try now. The "large" field should have 100% width.
